### ISSUE TITLE
Not compatible with pages which are a parent of course

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-quicknav#1]
Looks like this crashes when a footer is assigned to a contentObject which is a parent of course. Not sure if we should always have a contentObject of _type:menu assigned to course rather than individual pages directly (if using multiple contentObjects), but if not, then it is possible to create issues with this.

**Comment by moloko** [comment]
is this still an issue?

**Comment by oliverfoster** [comment]
fixed in #30

**Comment by oliverfoster** [comment]
not fixed

**Comment by oliverfoster** [comment]
lol

**Comment by moloko** [comment]
closing as refers to old version of quick nav
