### ISSUE TITLE
Doesn't show after a ABS or AR at end of page

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-quicknav#13]
If a Article Block Slider or Article Reveal is used at the bottom of the page QuickNav will not show below  it. 

Current workaround is having an empty article + block with a blank component below it. It would be better if this could just be avoided.

**Comment by simondate** [comment]
@oliverfoster do you know if this will ever be fixed?

**Comment by oliverfoster** [comment]
It will if anyone has the time to pick it up. You're more than welcome to have a go. Basically it just needs turning into a component or a proper page footer. It also needs rewriting so it's easier to read.

**Comment by oliverfoster** [comment]
I think I'd go for a page footer.

**Comment by oliverfoster** [comment]
Just as a side note. If you put a new article, block and blank after the ABS or AR it will work just fine as is.

**Comment by oliverfoster** [comment]
this is resolved in issue/25 as quicknav is now a component.
