### ISSUE TITLE
needs to integrate with the pageIncompletePrompt extension

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-quicknav#2]
currently you get no 'page incomplete' warning if you leave the page by clicking on one of the quickNav buttons

**Comment by develop-stuartohare** [comment]
fixed in ed2bb6b10b2faff02d38b698b42eb3dfa4351aec, https://github.com/cgkineo/adapt-framework-kineoFork/commit/7dd3b9bf98026fa7f82efd9c79aef22c5428b245, https://github.com/cgkineo/adapt-pageIncompletePrompt/commit/372d759c385ed86e17a42d23281f8fa7f48ed888
