### ISSUE TITLE
Quicknav used in conjunction with the Article Reveal Extension

### ISSUE THREAD

**Issue by joe-replin** [cgkineo/adapt-quicknav#20]
Hello,

If an article reveal is used at the bottom of a page, the quicknav extension will be placed inside of the article reveal. It is easy enough to create a new blank article after as a workaround so this ticket is just an idea really. Would it be possible to create an exception where quicknav is placed outside of an article reveal?

**Comment by oliverfoster** [comment]
It is possible but...
We really don't like extensions being aware of each other where possible (especially for behavioral exceptions). It makes writing documents and explaining it to other people pretty complicated and it also makes debugging really hard and it's also very difficult to figure out the final behaviour when there are a lot of intertwining rules.

**Comment by joe-replin** [comment]
Hello Oliver. That is good to be aware of and I'll keep this in mind in the future. Thank you for the quick response!

**Comment by oliverfoster** [comment]
No worries 👍 :)
