### ISSUE TITLE
No longer working with contentObjects.json

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-quicknav#35]
It seems that the quick nav is no longer working when applied to content objects in contentObjects.json.  Instead, it's required to create a new component to house the quick nav.  In previous versions, adding to a content object worked fine.

Here is what I'm adding to a typical content object:

```
        "_quicknav": {
		    "_isEnabled": true,
		    "_isContinuous": "global",
		    "_injectIntoSelector": "",
	        "_global": {
		        "_pageNext":"co-300",
		        "_pagePrevious": "co-100"
		    }, 
		    "_buttons": {
		    	"_hasIcons": true,
		        "_root": {
		            "_isHidden": false,
		            "text": "Menu",
		            "_icon": "icon-home"
		        },
		        "_up": {
		            "_isHidden": true,
		            "text": "Back to menu",
		            "_icon": "icon-home"
		        },
		        "_previous": {
		            "_isHidden": false,
		            "text": "Previous Topic",
		            "_icon": "icon-controls-left"
		        },
		        "_next": {
		            "_isHidden": false,
		            "text": "Next Topic",
		            "_icon": "icon-controls-right"
		        }
		    }
		}
```

Note that I am _not_ using an article reveal or a block slider.

**Comment by moloko** [comment]
hi @swashbuck yes that was a deliberate change as part of #28 - I think 'injecting' it into the page was causing a lot a problems, I can't recall specifics though.

**Comment by swashbuck** [comment]
Ok, thanks for the quick reply.  I'll pass this along to the team.
