### ISSUE TITLE
Previous button not working on second page only

### ISSUE THREAD

**Issue by moshelerato** [cgkineo/adapt-quicknav#36]
Hi,

Im sort of new to adapt but have worked quite a bit on it, two projects to be exact.

I tried copying and pasting working code from the other previous buttons and it still wont workon the second page only, the rest are fine. 

Is this a common issue.

Thanks in advance for your assistance.

**Comment by moloko** [comment]
> Is this a common issue.
No... 

If you could tell us which version of quicknav you're using (version number is in bower.json) and send over your configuration then someone will try to take a look. It would also help to have a copy of your contentObjects.json too.

It would also help to know more specifically what you mean by 'won't work'... does the button not appear? does it appear but do nothing when clicked? are there any errors in the browser console?

**Comment by moshelerato** [comment]
Thanks, Moloko, I wrote it in a rush as I'm currently rushing between projects. Let me have a look and I will share right away. 

To answer your question about what is exactly happening, the button appears but does nothing when it's clicked, I will also check the debugger for error logs.

**Comment by oliverfoster** [comment]
If you check the example.json you might have some clues about how each version should be configured.

**Comment by moshelerato** [comment]
Hi found this in the bower.json

{
  "name": "adapt-quicknav",
  "repository": "git://github.com/cgkineo/adapt-quicknav",
  "framework": "^2.0.0",
  "version": "2.0.2",
  "homepage": "https://github.com/cgkineo/adapt-quicknav",
  "issues": "https://github.com/cgkineo/adapt-quicknav/issues/",
  "displayName": "Quick navigation",
  "extension": "quicknav",
  "description": "Navigation bar that is displayed within Adapt content pages, typically at the bottom.",
  "main": "/js/adapt-quicknav.js",
  "keywords": [
    "adapt-plugin",
    "adapt-extension"
  ],
  "license": "GPLv3",
  "targetAttribute": "_quicknav"
}

**Comment by moshelerato** [comment]
Hi, I have attached the contentobjects file it didn't accept the .json extension so i converted to .txt.

[contentObjects.txt](https://github.com/cgkineo/adapt-quicknav/files/1336512/contentObjects.txt)

**Comment by moshelerato** [comment]
This is the error message I receive:

adapt-quicknav.js:157 Uncaught TypeError: Cannot read property 'get' of undefined
    at n.isPageAvailable (adapt-quicknav.js:157)
    at n.getPrevPageIndex (adapt-quicknav.js:105)
    at n.onPreviousClicked (adapt-quicknav.js:34)
    at n.onPreviousClicked (adapt-quicknav-view.js:75)
    at HTMLDivElement.dispatch (jquery.v2.js:3)
    at HTMLDivElement.r.handle (jquery.v2.js:3)

**Comment by moshelerato** [comment]
@oliverfoster, that's what I pretty much did before using the quick nav, since I got the other pages to work if that makes sense.

**Comment by moshelerato** [comment]
Hi Guys,

Please advise, I could really use your help.

**Comment by moshelerato** [comment]
Thanks, @oliverfoster, I will test and get back to you.

**Comment by moloko** [comment]
as @oliverfoster says you are using quite an old version and so ideally should use the latest.

however, I had a look at the files you supplied and the issue likely lies in line 71 of your contentObjects.json where you have the `_pagePrevious` setting for co-10 set to `"co-10"` i.e. you are telling it the page to go to when the previous button is clicked is the page the user is currently on.

IIRC you don't actually need to set `_pageNext` or `_pagePrevious` unless you want the next/previous button to send the user to a page that's outside of the 'normal flow' of the content.

**Comment by moshelerato** [comment]
Muchos Gracias, or in south africa, buy a donkey. You guys Rock the house party.

**Comment by moloko** [comment]
Haha no problem

Leaf lick a duck!

**Comment by MonkBrachiss** [comment]
@moloko. I'm working on the same project moshe is working on and we are trying to overcome the same issue. I updated the quicknav and changed the co-10 to point to co-05 which is the _pagePrevious ID. It still wont work.

**Comment by moloko** [comment]
> I updated the quicknav

If you updated the quicknav to the latest version then setting `_pagePrevious` will have no effect, the configuration for the new version is completely different, please see example.json for the new configuration.

**Comment by MonkBrachiss** [comment]
I managed to get a part of the quicknav right. I'm now facing a different issue. The _Previous button is lock. how do i fix this,

**Comment by oliverfoster** [comment]
You can make custom buttons by adding a new entry and calling it something different, use "_customRouteId" to set the location.

```json
"_buttons": {
    "_customPrev": {
        "_isEnabled": true,
        "_order": 1,
        "_classes": "",
        "_iconClass": "",
        "_alignIconRight": false,
        "text": "< Previous",
        "ariaLabel": "Previous Page",
        "_showTooltip": true,
        "tooltip": "{{displayTitle}}",
        "_customRouteId": "co-10"
    }
}   
```

or look at the "_loopType" property:

https://github.com/cgkineo/adapt-quicknav/blob/master/example.json#L14-L17

**Comment by MonkBrachiss** [comment]
Thank you so much.. :). workis best for me.
