### ISSUE TITLE
Installing plugin on new framework

### ISSUE THREAD

**Issue by OscarArango** [cgkineo/adapt-quicknav#48]
Generates an error upon installation. "Plugin upload failed" is the error.

**Comment by oliverfoster** [comment]
Have you successfully installed any other plugin?

**Comment by OscarArango** [comment]
yes, several others.  for example: search plugin, glossary plugin, Hints etc.  Your plugin is used alot for our courses so it's kinda of a bummer.  No specific error message either, just "Plugin upload failed".

**Comment by oliverfoster** [comment]
I've just uploaded the master branch on an AAT instance.

![image](https://user-images.githubusercontent.com/7974663/36210884-85d40090-1197-11e8-9bf7-efee6bb487c7.png)

[adapt-quicknav.zip](https://github.com/cgkineo/adapt-quicknav/files/1724428/adapt-quicknav.zip)

**Comment by moloko** [comment]
@OscarArango anything further on this or can we close please?
