### ISSUE TITLE
unstable _order sorting 

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-quicknav#49]
### Subject of the issue/enhancement/features
In Chrome it looks like the sort which takes place on the `_order` of each item can cause issues with the expected order. Seems fine on other supported browsers.

### Steps to reproduce
If more than 5 `_siblings` (actually linked to the data array containing more than 10 items) the index order of the siblings is not maintained during the sort.

**Comment by oliverfoster** [comment]
Sounds like it's sorting by string instead of number. 
Can you show an example or find the cause?

**Comment by danielghost** [comment]
Think it is to do with Chrome and how it uses a faster unstable Quicksort alogorithm for arrays of more than 10 items. Will look into how we can workaround this.

**Comment by oliverfoster** [comment]
Ahh, that's not good.

**Comment by moloko** [comment]
fixed by 2d532f8e86f883a164bda3ea0a00ad6acc90394a
