### ISSUE TITLE
Ability to hide previous and next buttons

### ISSUE THREAD

**Issue by paul-mediakitchen** [cgkineo/adapt-quicknav#55]
It would be great to have the option to hide the previous and next button/icons in the same way you can hide the up button and the home button.

**Comment by moloko** [comment]
@paul-mediakitchen all the buttons have an `_isEnabled` property that allows you to control whether they are shown or not.

I'm assuming you're using the AAT so it's possible there's something wrong with the properties.schema - I've had a quick look and I can't see anything obvious but if there is a problem please log a ticket giving as much detail as possible about your environment, what you've done (with screenshots where helpful) and what version of the extension you're using
