### ISSUE TITLE
Unable to preview when quicknav added

### ISSUE THREAD

**Issue by barryjenkin** [cgkineo/adapt-quicknav#60]
Having upgraded to latest AT and vanilla 3.0.0 theme, and using quicknav 3.0.5, just struggling to preview / view a published course once quicknav component has been added. 

I get as far as the menu but can't open a page that includes quicknav (when set to one of its button options). Without quicknav (or when no quicknav settings are selected) the page opens fine. This took me a while to figure out as I'm only getting a loading symbol and no error message. Logs and browser console aren't giving much away either. It's happening on both new and pre-existing projects.

Any clues as to what this might be? 

*** just got it working when I went back a couple of quicknav versions **

**Comment by oliverfoster** [comment]
I need to know the version works to figure out what the differences might be.

The schema changed quite dramatically at some point.

**Comment by barryjenkin** [comment]
I went back to 3.0.3 which previews fine. It's possible 3.0.4 works also - I just returned to my last working version.

**Comment by oliverfoster** [comment]
https://github.com/cgkineo/adapt-quicknav/compare/dd5f56fc7992b8d4530e9ed11f6fb20dab27f55e...e4dc1f9068303913d0ef6542ea2edfc09328987a < this is the diff between 3.0.3 and 3.0.5
I can't see anything that'd cause issue.

**Comment by barryjenkin** [comment]
Hmm. I just reinstalled 3.0.5 and created a new project with Vanilla and still the same. The course opens but the page containing quicknav doesn't. I removed 3.0.5 and repeated steps with v3.0.3 and the page opens fine.

**Comment by barryjenkin** [comment]
Yes it's the master. I've been uploading the zip via the plugin uploader on the authoring tool (0.5.0).

**Comment by oliverfoster** [comment]
You'll want to use version 3.0.5 from the releases tab, don't use master, it's not yet compatible with the framework version you have.

**Comment by barryjenkin** [comment]
Great - did that and all works fine. Thanks! :)
