### ISSUE TITLE
Buttons in wrong order using Chrome

### ISSUE THREAD

**Issue by SteveX** [cgkineo/adapt-quicknav#69]
Using 3 buttons: < Previous, Go to main menu, and Next > on Adapt Authoring 0.6.0, framework 3.2, Quicknav 3.1

When viewing in Chrome 69 Mac Sierra or on Chrome 67 or 69 on Windows 10 the Previous button is displayed last. They are ordered correctly in all other browsers.

**Comment by moloko** [comment]
Just tried this myself, using Chrome 69 for Win 10 - not seeing a problem:
![image](https://user-images.githubusercontent.com/1249597/46542567-9be6d700-c8b6-11e8-9960-04b804e779b3.png)

could you send through the .json for the component so we can have a look?

**Comment by moloko** [comment]
could be that #49 is not as fixed as we thought...

**Comment by danielghost** [comment]
Wondering if linked to this the fix for this:
https://github.com/cgkineo/adapt-quicknav/issues/49

Might be that if there are less than 10 items and `"_order": 1` is set for each item, the sort order is incorrect. Probably need to add a condition for the previous fix so it only does this in certain conditions.

**Comment by danielghost** [comment]
Couldn't replicate the issue as described by @SteveX, but there were still symptoms of an unstable sort in Chrome. This can be seen in the screenshot by @moloko.

It seems Chrome's unstable Array sort implementation may be sorted in v70 (soon to be released), but have added a fix for now so we aren't reliant on this. Now uses Underscore.js sortBy. We can look to revert back to the native browser implementation at a later date should this prove stable.
