### ISSUE TITLE
Tooltip position incorrect

### ISSUE THREAD

**Issue by SteveX** [cgkineo/adapt-quicknav#70]
When using the tooltips and a 3 button setup the tooltip for the first button is way too far to the right. 
Safari/Chrome on Mac and Firefox on Windows using Quicknav 3.1 on AT 0.6.0 Framework 3.2

Also happens on Safari Mac using Quicknav 3.0.5 on AT 0.5.0 Framework 3.0

**Comment by moloko** [comment]
could be that #49 is not as fixed as we thought...
