### ISSUE TITLE
Feature request: to be able to implement locking on a start page

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-quicknav#78]
I think I'm right in saying that currently there's no way to implement any kind of locking of the quick nav buttons on the intro page of course that has the structure Intro page > Menu > Other pages...?

It would be extremely useful to be able to do this since you typically want to be quite hot about preventing the learner from getting past the intro page without having completed everything - as the intro page isn't typically shown on the menu (when there is a link back to it, there's generally no progress indicator). So if the learner does miss something they've got no way of knowing that what they missed was in the intro page.

(Yes you can put pageIncompletePrompt in - but the learner might ignore that and move forward anyway)

Here's my solution - which I'm not particularly happy with, it's just to get the conversation started!
```js
Handlebars.registerHelper('shouldBeLocked', function(options) {
    if (this._isLocked) {
        return options.fn(this);
    }

    if (this._isDisabledUntilPageComplete && !Adapt.findById(this._isDisabledUntilPageComplete).get('_isComplete')) {
        return options.fn(this);
    }

    return options.inverse(this);
});
```
And here's the JSON:
```json
"_buttons": {
    "_root": {
        "_isEnabled": true,
        "_isDisabledUntilPageComplete": "co-100",
        "_order": 1,
        "_classes": "btn-text",
        "_iconClass": "",
        "_alignIconRight": false,
        "text": "Continue",
        "ariaLabel": "Continue",
        "_showTooltip": false
    }
}
```

**Comment by moloko** [comment]
Just it case it's not clear, the `shouldBeLocked` HBS helper is intended to be used in quicknav-item.hbs in place of `{{#if _isLocked}}`

**Comment by oliverfoster** [comment]
There is a locking render for _isLocked properties which might be informative:

https://github.com/cgkineo/adapt-quicknav/blob/master/js/view.js#L35 < Listen for locking
https://github.com/cgkineo/adapt-quicknav/blob/master/js/view.js#L64 < Check button states
https://github.com/cgkineo/adapt-quicknav/blob/master/js/view.js#L89-L111 < Rerender and update buttons from template

It might work just to add a rule to the data in the model https://github.com/cgkineo/adapt-quicknav/blob/master/js/model.js#L92, something like:
```js
                var isDisabledUntilPageComplete = buttonConfig._isDisabledUntilPageComplete &&
                    !Adapt.findById(buttonConfig._isDisabledUntilPageComplete).get('_isComplete');

                _.extend(item, buttonConfig, {
                    type: attrName,
                    index: 0,
                    order: order++,
                    isDisabledUntilPageComplete: isDisabledUntilPageComplete
                });
```
With this in the template:

```hbs
{{#any _isLocked isDisabledUntilPageComplete}}
{{#if _isLocked}}{{@root/_globals._accessibility._ariaLabels.locked}}{{else isDisabledUntilPageComplete}}{{@root/_globals._accessibility._ariaLabels.locked}}{{else if _isComplete}}
```

**Comment by moloko** [comment]
> Are you sure you wanted to be able to specify an id?

I didn't really want to have to... but when the button on the intro page you want to lock is the _root button, the data model made available to handlebars is that of Adapt.course - so I needed some way of being able to look up which page I should be checking completion for. 

Doing the calculation in model.js as you suggest above may give me more options.

**Comment by oliverfoster** [comment]
```js
var isCurrentPageComplete = this.getCurrentPage().get("_isComplete");
```

**Comment by moloko** [comment]
how about this? (to go in model.js L92)
```js
_.extend(item, buttonConfig, {
    type: attrName,
    index: 0,
    order: order++,
    locked: item._isLocked || (buttonConfig._lockUntilPageComplete && !buttonTypeModels._page.get('_isComplete'))
});
```

**Comment by oliverfoster** [comment]
Yea, that sounds like a good plan. If you store `buttonTypeModels._page.get('_isComplete')` in a variable outside the loop that'd be more performant and easier to read.

You gonna switch the `_isLocked` references in the handlebars for just `locked`?

**Comment by moloko** [comment]
> Yea, that sounds like a good plan. If you store `buttonTypeModels._page.get('_isComplete')` in a variable outside the loop that'd be more performant and easier to read.

good call, I'll do that
> You gonna switch the `_isLocked` references in the handlebars for just `locked`?

Yes. You can see the current implementation in uk-lcel-406418 if you want to take a look.

**Comment by oliverfoster** [comment]
It all sounds fine - a nice addition.
